std_msgs/Header header
  
float64    process_status                                               
float64    spinning_mode                         
float64    navigation_staus    
float64    location_staus              
float64    auto_aim                  
float64    robot_x            
float64    robot_y             
float64    robot_vx        
float64    robot_vy          
float64    robot_vw          
float64    robot_gyro_yaw    
