# std_msgs/Header header

# float64 game_type
# float64 game_progress
# float64 shooter_cooling_rate
# float64 shooter_speed_limit
# float64 shooter_cooling_limit
# float64 robot_id
# float64 remain_hp
# float64 max_hp
# float64 armor_id
# float64 hurt_type
# float64 bullet_freq
# float64 bullet_speed
# float64 bullet_remaining_num
# string  key_board
# float64 other_robot_id
# float64 tgx
# float64 tgy
# float64 tgz
# float64 game_time
# float64 enemy_sentry_hp
# float64 enemy_outpost_hp
# float64 self_outpost_hp
std_msgs/Header header
float64 game_state
float64 game_time
float64 remain_hp